language: node_js
node_js:
- '12'
script:
- yarn test
- yarn run package
deploy:
  # UAT Buckets
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ap-northeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ap-northeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-2
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ap-south-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-south-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ap-southeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ap-southeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-ca-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ca-central-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-eu-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-central-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-eu-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-eu-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-2
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-eu-west-3
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-3
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-sa-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: sa-east-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-us-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-us-east-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-us-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-1
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $UAT_AWS_ACCESS_KEY
    secret_access_key: $UAT_AWS_SECRET_KEY
    bucket: com-netuitive-uat-use1-lambda-assets-us-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-2
    on:
      repo: metricly/lambda-utilization
      branch: develop
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ap-northeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ap-northeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ap-south-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-south-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ap-southeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ap-southeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-ca-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ca-central-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-eu-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-central-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-eu-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-eu-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-eu-west-3
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-3
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-sa-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: sa-east-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-us-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-us-east-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-us-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $APP_AWS_ACCESS_KEY
    secret_access_key: $APP_AWS_SECRET_KEY
    bucket: com-netuitive-app-usw2-lambda-assets-us-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ap-northeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ap-northeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-northeast-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ap-south-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-south-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ap-southeast-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ap-southeast-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-ca-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: ca-central-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-eu-central-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-central-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-eu-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-eu-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-eu-west-3
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: eu-west-3
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-sa-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: sa-east-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-us-east-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-us-east-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-us-west-1
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-1
    on:
      repo: metricly/lambda-utilization
      tags: true
  - provider: s3
    access_key_id: $EU_AWS_ACCESS_KEY
    secret_access_key: $EU_AWS_SECRET_KEY
    bucket: com-netuitive-eu-euw1-lambda-assets-us-west-2
    local-dir: public
    upload-dir: lambda-utilization
    acl: public_read
    skip_cleanup: true
    region: us-west-2
    on:
      repo: metricly/lambda-utilization
      tags: true